import os
import sys
import pathlib



d = "../data/sim_remaining/msa"
res_d = "../data/sim_remaining/bootstrapping"
msa_paths = [os.path.join(d, fn) for fn in os.listdir(d)]
msa_names = [str(os.path.split(pth)[1]).split(".")[0] for pth in msa_paths]
msa_names = [name for name in msa_names if name != ""]
msa_paths = [os.path.join(msa_path, "gtr_g_sim_msa.fasta") for msa_path in msa_paths]
msas = dict(zip(msa_names, msa_paths))

raxmlng_prefix = pathlib.Path(res_d) / "{msa}"/ "bootstrap"

rule all:
    input:
        expand(raxmlng_prefix.with_suffix(".raxml.bootstraps"), msa=msa_names),




rule bootstrapping:
    output:
        raxml_bootstraps = raxmlng_prefix.with_suffix(".raxml.bootstraps"),
    params:
        prefix  = str(raxmlng_prefix),
        msa     = lambda wildcards: msas[wildcards.msa],
    log:
        raxml_log = raxmlng_prefix.with_suffix(".raxml.bootstraps.log")
    threads: 8
    resources:
        mem_mb = 4000,
        disk_mb = 4000,
        run_time = 480,
    shell:
        "./raxml-ng --all "
        "--msa {params.msa} "
        "--model  GTR+G "
        "--bs-trees 100 "
        "--bs-metric fbp "
        "--prefix {params.prefix} "
        "--seed 2 "
        "--threads 8 "
        "--force model_lh_impr "
        #"--force perf_threads "
        "> {log.raxml_log} "








